"use client";

import { FormEvent, useEffect, useState } from "react";
import api from "@/lib/api";
import { Button } from "@/components/ui/Button";

type Plan = { id:number; subject_id:number|null; module_offering_id:number|null; batch_id:number; planned_sessions:number; conducted_sessions:number; deficit:number };
type Option = { id:number; name?:string; code?:string; title?:string };
type Offering = { id:number; module_code:string; module_title:string; batch_id:number; batch_name:string; intake_code:string; semester_number:number; is_active:boolean };
type Suggestion = { id:number; suggested_date:string; suggested_start_time:string; suggested_room:string; status:string };

export default function Page(){
  const [plans,setPlans]=useState<Plan[]>([]);const [offerings,setOfferings]=useState<Offering[]>([]);const [subjects,setSubjects]=useState<Option[]>([]);const [batches,setBatches]=useState<Option[]>([]);const [suggestions,setSuggestions]=useState<Record<number,Suggestion>>({});const [error,setError]=useState("");const [form,setForm]=useState({module_offering_id:"",planned_sessions:""});
  const batchName=(id:number)=>batches.find(x=>x.id===id)?.name??`#${id}`;
  const courseName=(plan:Plan)=>{const offering=offerings.find(x=>x.id===plan.module_offering_id);if(offering)return `${offering.module_code} — ${offering.module_title}`;const subject=subjects.find(x=>x.id===plan.subject_id);return subject?`${subject.code} — ${subject.name}`:`#${plan.subject_id}`};
  async function load(){try{const [planResponse,offeringResponse,subjectResponse,batchResponse]=await Promise.all([api.get("/api/v1/course-completion/plans"),api.get("/api/v1/academic/module-offerings"),api.get("/api/v1/academic/subjects"),api.get("/api/v1/academic/batches")]);setPlans(planResponse.data);setOfferings(offeringResponse.data.filter((entry:Offering)=>entry.is_active));setSubjects(subjectResponse.data);setBatches(batchResponse.data)}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to load course plans")}}
  useEffect(()=>{void load()},[]);
  async function submit(event:FormEvent){event.preventDefault();const offering=offerings.find(entry=>entry.id===Number(form.module_offering_id));if(!offering||Number(form.planned_sessions)<1){setError("Select an active module offering and enter a positive planned session count.");return}try{await api.post("/api/v1/course-completion/plans",{module_offering_id:offering.id,batch_id:offering.batch_id,planned_sessions:Number(form.planned_sessions)});setForm({module_offering_id:"",planned_sessions:""});setError("");await load()}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to create course plan")}}
  async function suggest(id:number){try{const {data}=await api.post(`/api/v1/course-completion/plans/${id}/suggest-makeup`);setSuggestions({...suggestions,[id]:data})}catch(requestError:any){setError(requestError.response?.data?.detail??"No conflict-free slot is available")}}
  async function decide(planId:number,status:string){try{const {data}=await api.patch(`/api/v1/course-completion/suggestions/${suggestions[planId].id}`,{status});setSuggestions({...suggestions,[planId]:data});setError("")}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to decide suggestion")}}
  return <div className="max-w-6xl"><h1 className="mb-2 text-3xl font-bold">Course completion</h1><p className="mb-6 text-slate-400">Plans now follow the same module offerings and canonical routine used for attendance.</p><form onSubmit={submit} className="mb-8 grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-5 md:grid-cols-3"><select required className="rounded bg-slate-950 p-2" value={form.module_offering_id} onChange={event=>setForm({...form,module_offering_id:event.target.value})}><option value="">Active module offering</option>{offerings.map(entry=><option key={entry.id} value={entry.id}>{entry.module_code} — {entry.module_title} · {entry.batch_name} · Sem {entry.semester_number}</option>)}</select><input required min="1" className="rounded bg-slate-950 p-2" type="number" placeholder="Planned sessions" value={form.planned_sessions} onChange={event=>setForm({...form,planned_sessions:event.target.value})}/><Button>Create plan</Button></form>{error&&<p className="mb-4 text-red-400">{error}</p>}<div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-700 text-slate-400"><th className="p-3">Course</th><th className="p-3">Batch</th><th className="p-3">Planned</th><th className="p-3">Conducted</th><th className="p-3">Deficit</th><th className="p-3">Makeup suggestion</th></tr></thead><tbody>{plans.map(plan=>{const suggestion=suggestions[plan.id];return <tr key={plan.id} className="border-b border-slate-800"><td className="p-3">{courseName(plan)}</td><td className="p-3">{batchName(plan.batch_id)}</td><td className="p-3">{plan.planned_sessions}</td><td className="p-3">{plan.conducted_sessions}</td><td className="p-3 font-semibold">{plan.deficit}</td><td className="p-3">{!suggestion?<Button onClick={()=>void suggest(plan.id)}>Suggest makeup</Button>:<div>{suggestion.suggested_date} {suggestion.suggested_start_time} · {suggestion.suggested_room}<span className="ml-2 capitalize text-slate-400">{suggestion.status}</span>{suggestion.status==="pending"&&<div className="mt-2 space-x-3"><button onClick={()=>void decide(plan.id,"approved")} className="text-emerald-400">Approve</button><button onClick={()=>void decide(plan.id,"rejected")} className="text-red-400">Reject</button></div>}</div>}</td></tr>})}{!plans.length&&<tr><td colSpan={6} className="p-5 text-center text-slate-400">No course plans yet.</td></tr>}</tbody></table></div></div>;
}
