"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import api from "@/lib/api";
import {PageHeader} from "@/components/ui/PageHeader";
import {Badge} from "@/components/ui/Badge";
import {EmptyState,ErrorState,LoadingState} from "@/components/ui/States";
const localDate=(value=new Date())=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;
export default function Page(){
  const[rows,setRows]=useState<any[]>([]),[data,setData]=useState<Record<string,any[]>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError("");try{const today=localDate(),names=["modules","teachers","class-types"],responses=await Promise.all([...names.map(name=>api.get(`/api/v1/academic/${name}`)),api.get(`/api/v1/academic/routine-occurrences?date_from=${today}&days=8`)]);setData(Object.fromEntries(names.map((name,index)=>[name,responses[index].data])));setRows(responses.at(-1)?.data||[])}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to load canonical timetable")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);const find=(key:string,id:number)=>data[key]?.find(item=>item.id===id),name=(key:string,id:number)=>{const item=find(key,id);return item?(key==="modules"?item.title:item.name):"—"};const today=rows.filter(item=>item.date===localDate()),upcoming=rows.filter(item=>item.date!==localDate()&&!item.cancelled).slice(0,5);
  const item=(occurrence:any)=><article key={`${occurrence.routine_id}-${occurrence.date}`} className="border-t border-slate-800 px-5 py-4 first:border-t-0"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-slate-200">{occurrence.date} · {occurrence.start_time.slice(0,5)}–{occurrence.end_time.slice(0,5)}</p><Badge tone={occurrence.cancelled?"danger":"neutral"}>{occurrence.cancelled?"Cancelled":name("class-types",occurrence.class_type_id)}</Badge></div><h3 className="mt-2 font-semibold">{name("modules",occurrence.module_id)}</h3><p className="mt-1 text-sm text-slate-400">{occurrence.section_names.join(" + ")} · {name("teachers",occurrence.teacher_id)} · {occurrence.room}</p></article>;
  return <div><PageHeader title="Administration dashboard" description="Today’s academic schedule and upcoming activity across the college." action={<Link href="/admin/routine" className="inline-flex min-h-10 items-center rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-emerald-300">Manage routine</Link>}/>{error&&<ErrorState title="Unable to load timetable" description={error} onRetry={()=>void load()}/>} {loading?<div className="grid gap-5 lg:grid-cols-2"><LoadingState/><LoadingState/></div>:<><section aria-label="Schedule metrics" className="mb-6 grid gap-4 sm:grid-cols-2"><div className="panel p-5"><p className="text-sm text-slate-400">Today&apos;s classes</p><p className="mt-2 text-3xl font-semibold">{today.length}</p></div><div className="panel p-5"><p className="text-sm text-slate-400">Upcoming classes shown</p><p className="mt-2 text-3xl font-semibold">{upcoming.length}</p></div></section><div className="grid gap-6 lg:grid-cols-2"><section className="panel overflow-hidden"><h2 className="px-5 py-4 text-lg font-semibold">Today&apos;s classes</h2>{today.map(item)}{!today.length&&<EmptyState title="No classes scheduled today" description="Routine occurrences for today will appear here."/>}</section><section className="panel overflow-hidden"><h2 className="px-5 py-4 text-lg font-semibold">Upcoming classes</h2>{upcoming.map(item)}{!upcoming.length&&<EmptyState title="No upcoming classes" description="The next scheduled occurrences will appear here."/>}</section></div></>}</div>;
}
