"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import api from "@/lib/api";
import {Button} from "@/components/ui/Button";
import {PageHeader} from "@/components/ui/PageHeader";
import {EmptyState,ErrorState,LoadingState} from "@/components/ui/States";
import {ConfirmDialog} from "@/components/ui/ConfirmDialog";

type Row=Record<string,string|number>;type Field={name:string;label:string;type?:"text"|"email"|"password"|"number";optionsEndpoint?:string};type Column={label:string;field:string;optionsEndpoint?:string};export type AcademicSetupConfig={title:string;singular:string;endpoint:string;fields:Field[];columns:Column[]};

export default function AcademicSetupPage({config}:{config:AcademicSetupConfig}){
  const[rows,setRows]=useState<Row[]>([]),[options,setOptions]=useState<Record<string,Row[]>>({}),[values,setValues]=useState<Record<string,string>>({}),[edit,setEdit]=useState<Row|null>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[deleteId,setDeleteId]=useState<number|null>(null);const size=20;
  const endpoints=useMemo(()=>[...new Set(config.fields.map(field=>field.optionsEndpoint).filter(Boolean)as string[])],[config.fields]);const columns=config.columns.filter(column=>column.field!=="id");
  const load=async(nextPage=page)=>{setLoading(true);setError("");try{const[first,...rest]=await Promise.all([api.get(`${config.endpoint}/page?page_number=${nextPage}&page_size=${size}`),...endpoints.map(endpoint=>api.get(endpoint))]);setRows(first.data.items);setTotal(first.data.total);setPage(nextPage);setOptions(Object.fromEntries(endpoints.map((endpoint,index)=>[endpoint,rest[index].data])))}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to load records")}finally{setLoading(false)}};
  useEffect(()=>{void load(1)},[config.endpoint]);
  const body=(source:Record<string,string|number>)=>Object.fromEntries(config.fields.flatMap(field=>{const value=String(source[field.name]??"").trim();return value?[[field.name,field.optionsEndpoint||field.type==="number"?Number(value):value]]:[]}));
  async function submit(event:FormEvent){event.preventDefault();const payload=body(values);if(Object.keys(payload).length!==config.fields.length){setError("Complete all required fields.");return}setSaving(true);setError("");try{if(edit)await api.patch(`${config.endpoint}/${edit.id}`,payload);else await api.post(config.endpoint,payload);setValues({});setEdit(null);await load(1)}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to save record")}finally{setSaving(false)}}
  async function remove(){if(deleteId==null)return;try{await api.delete(`${config.endpoint}/${deleteId}`);await load(page)}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to delete")}finally{setDeleteId(null)}}
  const display=(row:Row,column:Column)=>{const match=column.optionsEndpoint?options[column.optionsEndpoint]?.find(item=>item.id===row[column.field]):null;return match?match.name??match.code??"—":row[column.field]??"—"};
  return <div className="max-w-6xl"><PageHeader title={config.title} description={`Manage ${config.title.toLowerCase()} used across AntimBench.`}/><form onSubmit={submit} className="panel grid gap-4 p-5 md:grid-cols-2">{config.fields.map(field=><label key={field.name}><span className="field-label">{field.label}</span>{field.optionsEndpoint?<select required className="w-full" value={values[field.name]??""} onChange={event=>setValues({...values,[field.name]:event.target.value})}><option value="">Select {field.label.toLowerCase()}</option>{(options[field.optionsEndpoint]||[]).map(option=><option key={option.id} value={option.id}>{option.name??option.code}</option>)}</select>:<input required type={field.type??"text"} className="w-full" value={values[field.name]??""} autoComplete={field.type==="password"?"new-password":undefined} onChange={event=>setValues({...values,[field.name]:event.target.value})}/>}</label>)}<div className="flex items-end gap-3"><Button loading={saving}>{edit?"Save changes":`Create ${config.singular.toLowerCase()}`}</Button>{edit&&<Button type="button" variant="ghost" onClick={()=>{setEdit(null);setValues({})}}>Cancel</Button>}</div></form>{error&&<div className="mt-4"><ErrorState title="Unable to complete this action" description={error} onRetry={()=>void load(page)}/></div>}
    <div className="mt-7">{loading?<LoadingState label={`Loading ${config.title}`}/>:<div className="table-wrap"><table><thead><tr>{columns.map(column=><th key={column.field}>{column.label}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{columns.map(column=><td key={column.field}>{display(row,column)}</td>)}<td><div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={()=>{setEdit(row);setValues(Object.fromEntries(config.fields.map(field=>[field.name,String(row[field.name]??"")])));}}>Edit</Button><Button size="sm" variant="danger" onClick={()=>setDeleteId(Number(row.id))}>Delete</Button></div></td></tr>)}{!rows.length&&<tr><td colSpan={columns.length+1} className="p-0"><EmptyState title={`No ${config.title.toLowerCase()} yet`} description={`Create the first ${config.singular.toLowerCase()} using the form above.`}/></td></tr>}</tbody></table></div>}</div>
    <div className="mt-4 flex items-center justify-between gap-3"><Button variant="outline" disabled={page===1||loading} onClick={()=>void load(page-1)}>Previous</Button><span className="text-sm text-slate-400">Page {page} of {Math.max(1,Math.ceil(total/size))}</span><Button variant="outline" disabled={page*size>=total||loading} onClick={()=>void load(page+1)}>Next</Button></div>
    <ConfirmDialog open={deleteId!=null} title={`Delete this ${config.singular.toLowerCase()}?`} description="This action can only succeed when no related records depend on it." confirmLabel="Delete" tone="danger" onClose={()=>setDeleteId(null)} onConfirm={remove}/>
  </div>;
}
