"use client";

import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import api from "@/lib/api";
import QRDisplay from "@/components/QRDisplay";
import {Button} from "@/components/ui/Button";
import {Badge,StatusBadge} from "@/components/ui/Badge";
import {PageHeader} from "@/components/ui/PageHeader";
import {EmptyState} from "@/components/ui/States";
import {ConfirmDialog} from "@/components/ui/ConfirmDialog";

type Row={attendance_id:number|null;student_id:number;student_name:string;roll_number:string;status:string};
type ExceptionRow={id:number;student_name:string;roll_number:string;section_name:string;reason:string;distance_meters:number|null;allowed_radius_meters:number|null;accuracy_meters:number|null;created_at:string;status:string};
type QRData={token:string;expires_at:string;rotation_seconds:number;module_title:string;section_names:string[];room:string;start_time:string;end_time:string;geofence_radius_meters:number|null;teacher_location_accuracy_meters:number|null};
type DialogAction={kind:"finalize"}|{kind:"exception";item:ExceptionRow;decision:"confirm"|"reject"}|{kind:"status";row:Row;status:string};
const meters=(value:number|null)=>value==null?"—":`${Math.round(value)}m`;

export default function Page(){
  const{id}=useParams<{id:string}>();const[qr,setQr]=useState<QRData|null>(null);const[rows,setRows]=useState<Row[]>([]);const[exceptions,setExceptions]=useState<ExceptionRow[]>([]);const[message,setMessage]=useState("");const[completed,setCompleted]=useState(false);const[countdown,setCountdown]=useState(0);const[dialog,setDialog]=useState<DialogAction|null>(null);
  async function refresh(){const[q,r,e]=await Promise.allSettled([api.get<QRData>(`/api/v1/sessions/${id}/qr`),api.get<Row[]>(`/api/v1/sessions/${id}/summary`),api.get<ExceptionRow[]>(`/api/v1/sessions/${id}/check-in-exceptions`)]);if(q.status==="fulfilled"){setQr(q.value.data);setCompleted(false)}else if(q.reason?.response?.status===409){setCompleted(true);setQr(null)}if(r.status==="fulfilled")setRows(r.value.data);if(e.status==="fulfilled")setExceptions(e.value.data)}
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>window.clearInterval(timer)},[id]);
  useEffect(()=>{const timer=window.setInterval(()=>setCountdown(qr?Math.max(0,Math.ceil((new Date(qr.expires_at).getTime()-Date.now())/1000)):0),250);return()=>window.clearInterval(timer)},[qr]);
  const counts=useMemo(()=>({present:rows.filter(row=>row.status==="present"||row.status==="late").length,pending:rows.filter(row=>row.status==="pending_verification").length,rejected:rows.filter(row=>row.status==="rejected").length,remaining:rows.filter(row=>row.status==="not_checked_in").length}),[rows]);
  async function finalize(){try{await api.post(`/api/v1/sessions/${id}/finalize`);setMessage("Session finalized successfully.");setCompleted(true);await refresh()}catch(error:any){setMessage(error.response?.data?.detail??"Unable to finalize this session")}}
  async function decide(item:ExceptionRow,decision:"confirm"|"reject",reason:string){try{await api.patch(`/api/v1/sessions/${id}/check-in-exceptions/${item.id}`,{decision,reason});setMessage(decision==="confirm"?`${item.student_name} confirmed present.`:`${item.student_name}'s attempt was rejected.`);await refresh()}catch(error:any){setMessage(error.response?.data?.detail??"Unable to review this attempt")}}
  async function change(row:Row,status:string,reason:string){if(!row.attendance_id)return;await api.patch(`/api/v1/attendance/${row.attendance_id}`,{status,reason});setMessage(`${row.student_name}'s attendance was updated.`);await refresh()}
  async function confirmAction(reason:string){if(!dialog)return;if(dialog.kind==="finalize")await finalize();else if(dialog.kind==="exception")await decide(dialog.item,dialog.decision,reason);else await change(dialog.row,dialog.status,reason)}
  const dialogInfo=dialog?.kind==="finalize"?{title:"Finalize attendance?",description:"Students who have not checked in will be finalized using the attendance rules. Resolve pending verifications first.",label:"Finalize session",tone:"danger" as const,reason:false}:dialog?.kind==="exception"?{title:dialog.decision==="confirm"?`Confirm ${dialog.item.student_name} present?`:`Reject ${dialog.item.student_name}'s attempt?`,description:"This decision is recorded in the attendance audit trail.",label:dialog.decision==="confirm"?"Confirm present":"Reject attempt",tone:dialog.decision==="confirm"?"primary" as const:"danger" as const,reason:true}:dialog?.kind==="status"?{title:`Change ${dialog.row.student_name} to ${dialog.status.replaceAll("_"," ")}?`,description:"Add a reason for this manual attendance correction.",label:"Save correction",tone:"primary" as const,reason:true}:null;
  return <div><PageHeader title={completed?"Session summary":"Live attendance session"} description={qr?`${qr.module_title} · ${qr.section_names.join(" + ")}`:"Attendance and location verification"} action={!completed&&<Button variant="outline" onClick={()=>setDialog({kind:"finalize"})}>Finalize session</Button>}/>{message&&<p role="status" className="mb-4 rounded-lg border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-200">{message}</p>}
    {qr&&<section className="panel my-6 grid items-center gap-8 p-5 sm:p-7 lg:grid-cols-[minmax(300px,420px)_1fr]"><div><QRDisplay value={qr.token}/><div className="mx-auto mt-3 max-w-[380px]"><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400 transition-[width]" style={{width:`${Math.max(0,Math.min(100,(countdown/qr.rotation_seconds)*100))}%`}}/></div><p className="mt-2 text-center text-sm font-medium text-emerald-300">Refreshes in {countdown} seconds</p></div></div><div><Badge tone="success">Session active</Badge><h2 className="mt-4 text-2xl font-semibold sm:text-3xl">{qr.module_title}</h2><p className="mt-2 text-lg text-slate-300">{qr.section_names.join(" + ")}</p><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wider text-slate-500">Time</dt><dd className="mt-1 font-medium">{qr.start_time.slice(0,5)}–{qr.end_time.slice(0,5)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-slate-500">Room</dt><dd className="mt-1 font-medium">{qr.room}</dd></div></dl>{qr.geofence_radius_meters!=null?<div className="mt-6 rounded-lg border border-emerald-500/25 bg-emerald-500/10 p-4"><p className="font-semibold text-emerald-300">Geofence active · {Math.round(qr.geofence_radius_meters)}m</p><p className="mt-1 text-sm text-slate-400">Captured with ±{Math.round(qr.teacher_location_accuracy_meters??0)}m accuracy</p></div>:<p className="mt-6 rounded-lg border border-amber-500/25 bg-amber-500/10 p-4 text-amber-200">Historical session: location attempts require teacher verification.</p>}</div></section>}
    <section aria-label="Attendance counts" className="mb-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Present",counts.present],["Pending verification",counts.pending],["Rejected attempts",counts.rejected],["Not checked in",counts.remaining]].map(([label,value])=><div key={String(label)} className="panel p-4"><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>)}</section>
    <section className="mb-8"><h2 className="mb-1 text-xl font-semibold">Location verification attempts</h2><p className="mb-3 text-sm text-slate-400">A student outside your selected boundary is held for review, not marked absent. Confirm only when you can verify the student is in class.</p><div className="table-wrap"><table><thead><tr><th>Student</th><th>Section</th><th>Reason</th><th>Distance from your location / boundary</th><th>Accuracy</th><th>Time</th><th>Actions</th></tr></thead><tbody>{exceptions.map(item=><tr key={item.id}><td>{item.student_name}<br/><span className="text-slate-400">{item.roll_number}</span></td><td>{item.section_name}</td><td><StatusBadge status={item.reason}/></td><td>{meters(item.distance_meters)} / {meters(item.allowed_radius_meters)}</td><td>{meters(item.accuracy_meters)}</td><td>{new Date(item.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</td><td>{item.status==="pending"?<div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>setDialog({kind:"exception",item,decision:"confirm"})}>Confirm present</Button><Button size="sm" variant="danger" onClick={()=>setDialog({kind:"exception",item,decision:"reject"})}>Reject</Button></div>:<StatusBadge status={item.status}/>}</td></tr>)}{!exceptions.length&&<tr><td colSpan={7} className="p-0"><EmptyState title="No location exceptions" description="Check-in issues will appear here for review."/></td></tr>}</tbody></table></div></section>
    <section><h2 className="mb-3 text-xl font-semibold">Live roster</h2><div className="table-wrap"><table><thead><tr><th>Student</th><th>Roll</th><th>Status</th><th>Correction</th></tr></thead><tbody>{rows.map(row=><tr key={row.student_id}><td className="font-medium text-slate-200">{row.student_name}</td><td>{row.roll_number}</td><td><StatusBadge status={row.status}/></td><td><select aria-label={`Correct attendance for ${row.student_name}`} disabled={!row.attendance_id} value={row.status} onChange={event=>setDialog({kind:"status",row,status:event.target.value})}><option value="not_checked_in">Not checked in</option><option value="pending_verification">Pending verification</option><option value="rejected">Rejected</option><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option><option value="bunk">Bunk</option></select></td></tr>)}</tbody></table></div></section>
    {dialogInfo&&<ConfirmDialog open title={dialogInfo.title} description={dialogInfo.description} confirmLabel={dialogInfo.label} tone={dialogInfo.tone} requireReason={dialogInfo.reason} onClose={()=>setDialog(null)} onConfirm={confirmAction}/>}</div>;
}
