"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import api from "@/lib/api";
import {PageHeader} from "@/components/ui/PageHeader";
import {Badge} from "@/components/ui/Badge";
import {EmptyState,ErrorState,LoadingState} from "@/components/ui/States";
const localDate=(value=new Date())=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;
export default function Page(){
  const[occurrences,setOccurrences]=useState<any[]>([]),[data,setData]=useState<Record<string,any[]>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError("");try{const today=localDate(),[catalogResponse,occurrenceResponse]=await Promise.all([api.get("/api/v1/academic/catalog"),api.get(`/api/v1/academic/routines/me/occurrences?date_from=${today}&days=8`)]);setData(catalogResponse.data);setOccurrences(occurrenceResponse.data||[])}catch(requestError:any){setError(requestError.response?.data?.detail??"Unable to load your routine")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);const find=(key:string,id:number)=>data[key]?.find(item=>item.id===id),name=(key:string,id:number)=>{const item=find(key,id);return item?(key==="modules"?item.title:item.name):"—"};const today=occurrences.filter(item=>item.date===localDate()),next=occurrences.find(item=>item.date>=localDate()&&!item.cancelled);
  const card=(item:any)=><article key={`${item.routine_id}-${item.date}`} className={`panel p-5 ${item.cancelled?"border-red-500/30 bg-red-500/5":""}`}><div className="flex items-start justify-between gap-3"><p className="text-lg font-semibold">{item.start_time.slice(0,5)}–{item.end_time.slice(0,5)}</p><Badge tone={item.cancelled?"danger":"info"}>{item.cancelled?"Cancelled":name("class-types",item.class_type_id)}</Badge></div><h3 className="mt-3 text-lg font-semibold">{name("modules",item.module_id)}</h3><p className="mt-2 text-sm text-slate-400">{name("teachers",item.teacher_id)} · {item.room}</p>{item.room!==item.original_room&&!item.cancelled&&<p className="mt-2 text-sm text-amber-300">Room changed from {item.original_room}</p>}</article>;
  return <div><PageHeader title="Student dashboard" description="Your classes, routine, and quickest path to attendance check-in." action={<Link href="/student/check-in" className="inline-flex min-h-10 items-center rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-emerald-300">Check in</Link>}/>{error&&<ErrorState title="Unable to load your schedule" description={error} onRetry={()=>void load()}/>} {loading?<LoadingState label="Loading student dashboard"/>:<><section><h2 className="mb-3 text-lg font-semibold">Today&apos;s classes</h2><div className="grid gap-4 md:grid-cols-2">{today.map(card)}{!today.length&&<div className="panel md:col-span-2"><EmptyState title="No classes scheduled today" description="Your next scheduled class will appear below."/></div>}</div></section><section className="mt-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Next class</h2><Link className="interactive-link text-sm" href="/student/routine">View full routine</Link></div>{next?card(next):<div className="panel"><EmptyState title="No upcoming class" description="Your assigned routine will appear here when available."/></div>}</section></>}</div>;
}
