"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import api from "@/lib/api";
import {storeToken} from "@/lib/auth";
import {PasswordInput} from "@/components/ui/PasswordInput";
import {AuthMain,Field} from "@/components/auth/AuthCard";
type Option={id:number;name:string};type Errors=Record<string,string>;
const input="w-full rounded-xl border border-slate-700 bg-slate-900 px-3 py-3 outline-none transition focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400";
export default function SignupPage(){const router=useRouter();const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[batch,setBatch]=useState("");const[section,setSection]=useState("");const[batches,setBatches]=useState<Option[]>([]);const[sections,setSections]=useState<Option[]>([]);const[errors,setErrors]=useState<Errors>({});const[serverError,setServerError]=useState("");const[loading,setLoading]=useState(false);const[loadingOptions,setLoadingOptions]=useState(true);
  useEffect(()=>{api.get("/api/v1/academic/batches").then(r=>setBatches(r.data)).catch(()=>setServerError("Unable to load college batches. Please try again.")).finally(()=>setLoadingOptions(false))},[]);
  useEffect(()=>{setSection("");setSections([]);if(batch)api.get(`/api/v1/academic/batches/${batch}/sections`).then(r=>setSections(r.data)).catch(()=>setServerError("Unable to load sections for this batch."))},[batch]);
  function validate(){const next:Errors={};if(!name.trim())next.name="Full name is required";if(!email.trim())next.email="Email is required";else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next.email="Enter a valid email address";if(!password)next.password="Password is required";else if(password.length<8)next.password="Password must be at least 8 characters";if(confirm!==password)next.confirm="Passwords do not match";if(!batch)next.batch="Select your batch";if(!section)next.section="Select your section";setErrors(next);return Object.keys(next).length===0}
  async function submit(e:FormEvent){e.preventDefault();setServerError("");if(!validate())return;setLoading(true);try{const{data}=await api.post("/api/v1/auth/signup",{name:name.trim(),email:email.trim(),password,batch_id:Number(batch),section_id:Number(section)});storeToken(data.access_token);router.push("/student/dashboard")}catch(err:any){setServerError(err.response?.data?.detail??"Unable to create your account. Please try again.")}finally{setLoading(false)}}
  const invalid=Object.values(errors).some(Boolean);
  const update=(key:string,setter:(v:string)=>void)=>(value:string)=>{setter(value);setErrors(current=>({...current,[key]:""}))};
  return <AuthMain><form noValidate onSubmit={submit} className="space-y-4"><header><p className="text-sm font-semibold text-emerald-400">STUDENT SIGNUP</p><h1 className="mt-2 text-3xl font-bold">Create your account</h1><p className="mt-2 text-sm text-slate-400">Student self-registration only. Teacher and staff accounts are created by an administrator.</p></header>{serverError&&<p role="alert" className="rounded-lg border border-red-900 bg-red-950/40 p-3 text-sm text-red-300">{serverError}</p>}<Field label="Full Name" error={errors.name}><input value={name} onChange={e=>update("name",setName)(e.target.value)} className={`${input} ${errors.name?"border-red-500":""}`} autoComplete="name"/></Field><Field label="Email" error={errors.email}><input value={email} onChange={e=>update("email",setEmail)(e.target.value)} className={`${input} ${errors.email?"border-red-500":""}`} type="email" autoComplete="email"/></Field><Field label="Password" error={errors.password}><PasswordInput value={password} onChange={e=>update("password",setPassword)(e.target.value)} onBlur={()=>validate()} className={`${input} ${errors.password?"border-red-500":""}`} autoComplete="new-password"/></Field><Field label="Confirm Password" error={errors.confirm}><PasswordInput value={confirm} onChange={e=>update("confirm",setConfirm)(e.target.value)} className={`${input} ${errors.confirm?"border-red-500":""}`} autoComplete="new-password"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Batch" error={errors.batch}><select disabled={loadingOptions} value={batch} onChange={e=>update("batch",setBatch)(e.target.value)} className={`${input} ${errors.batch?"border-red-500":""}`}><option value="">{loadingOptions?"Loading…":"Select batch"}</option>{batches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Section" error={errors.section}><select disabled={!batch} value={section} onChange={e=>update("section",setSection)(e.target.value)} className={`${input} ${errors.section?"border-red-500":""}`}><option value="">Select section</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div><button disabled={loading||invalid} className="w-full rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950 transition hover:bg-emerald-300 disabled:cursor-not-allowed disabled:opacity-50">{loading?"Creating account…":"Create Student Account"}</button><p className="text-center text-sm text-slate-400">Already have an account? <Link href="/login" className="font-semibold text-emerald-400 hover:text-emerald-300">Log in</Link></p></form></AuthMain>}
