"use client";
import { useCallback, useEffect, useState } from "react";
import api from "@/lib/api";
import { Button } from "@/components/ui/Button";
import { College, Field, Heading, Notice, Pager, errorMessage, inputClass } from "@/components/PlatformUI";
type Audit={id:number;college_name:string|null;actor_name:string|null;actor_id:number;action:string;entity_type:string;entity_id:number;details:string;created_at:string};
export default function AuditLog(){
 const [rows,setRows]=useState<Audit[]>([]);const [colleges,setColleges]=useState<College[]>([]);const [college,setCollege]=useState("");const [action,setAction]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [filters,setFilters]=useState({college:"",action:"",from:"",to:""});const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await api.get("/api/v1/platform/audit-logs",{params:{college_id:filters.college||undefined,action:filters.action||undefined,date_from:filters.from?new Date(filters.from+"T00:00:00").toISOString():undefined,date_to:filters.to?new Date(filters.to+"T23:59:59.999").toISOString():undefined,page}});setRows(r.data.items);setTotal(r.data.total);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[filters,page]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{api.get("/api/v1/platform/colleges").then(r=>setColleges(r.data)).catch(e=>setError(errorMessage(e)));},[]);
 return <><Heading title="System audit log">Review account access, college operations, and configuration changes across the platform. Audit history is read-only.</Heading><Notice error={error}/><form className="panel mb-5 grid items-end gap-4 p-5 sm:grid-cols-2 xl:grid-cols-5" onSubmit={e=>{e.preventDefault();setFilters({college,action,from,to});setPage(1);}}><Field label="College"><select className={inputClass} value={college} onChange={e=>setCollege(e.target.value)}><option value="">Entire platform</option>{colleges.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Action"><input className={inputClass} placeholder="e.g. created, login" value={action} onChange={e=>setAction(e.target.value)}/></Field><Field label="From"><input type="date" className={inputClass} value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Through"><input type="date" min={from||undefined} className={inputClass} value={to} onChange={e=>setTo(e.target.value)}/></Field><Button type="submit">Apply filters</Button></form><div className="panel overflow-x-auto" role="region" aria-label="Scrollable records" tabIndex={0}><table className="w-full text-left text-sm"><thead className="border-b"><tr>{["Time / actor","College","Action / record","Changes"].map(label=><th className="p-4" key={label}>{label}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={4} className="p-6">Loading audit history?</td></tr>:rows.length?rows.map(row=><tr key={row.id} className="border-b align-top last:border-0"><td className="whitespace-nowrap p-4"><p>{new Date(row.created_at).toLocaleString()}</p><p className="app-caption mt-1">{row.actor_name||`User #${row.actor_id}`}</p></td><td className="p-4">{row.college_name||"Platform"}</td><td className="p-4"><p className="font-semibold">{row.action}</p><p className="app-caption mt-1">{row.entity_type} #{row.entity_id}</p></td><td className="max-w-lg p-4"><details><summary className="cursor-pointer text-emerald-600">View changes</summary><pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap break-all text-xs">{(()=>{try{return JSON.stringify(JSON.parse(row.details),null,2);}catch{return row.details;}})()}</pre></details></td></tr>):<tr><td colSpan={4} className="p-6">No audit events match these filters.</td></tr>}</tbody></table></div><Pager page={page} total={total} onChange={setPage}/></>;
}
