"""course analytics crm schema

Revision ID: 36e89130504c
Revises: 0f378fa52e9c
Create Date: 2026-08-03 17:33:24.312888
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '36e89130504c'
down_revision: Union[str, None] = '0f378fa52e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'LATE'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('planned_sessions', sa.Integer(), nullable=False),
    sa.Column('conducted_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'batch_id', name='uq_course_plan_subject_batch')
    )
    op.create_table('student_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='casestatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='casepriority'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_case', 'student_cases', ['student_id', 'trigger_type', 'scope_type', 'scope_id'], unique=True, postgresql_where=sa.text("status IN ('open', 'in_progress')"), sqlite_where=sa.text("status IN ('open', 'in_progress')"))
    op.create_table('case_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['student_cases.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('makeup_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_plan_id', sa.Integer(), nullable=False),
    sa.Column('suggested_date', sa.Date(), nullable=False),
    sa.Column('suggested_start_time', sa.Time(), nullable=False),
    sa.Column('suggested_room', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('timetable_entry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='suggestionstatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_plan_id'], ['course_plans.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('makeup_suggestions')
    op.drop_table('case_interactions')
    op.drop_index('uq_active_case', table_name='student_cases', postgresql_where=sa.text("status IN ('open', 'in_progress')"), sqlite_where=sa.text("status IN ('open', 'in_progress')"))
    op.drop_table('student_cases')
    op.drop_table('course_plans')
    # ### end Alembic commands ###
