"""reports notifications guardian schema

Revision ID: 9647971e5956
Revises: 36e89130504c
Create Date: 2026-08-03 17:48:58.657984
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9647971e5956'
down_revision: Union[str, None] = '36e89130504c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('related_entity', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardians') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key('fk_guardians_user_id_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians') as batch_op:
        batch_op.drop_constraint('fk_guardians_user_id_users', type_='foreignkey')
        batch_op.drop_column('phone')
        batch_op.drop_column('user_id')
    op.drop_table('notifications')
    # ### end Alembic commands ###
